# Generated by Django 4.2 on 2023-05-27 21:08

from django.db import migrations, models
import lekipohodivplaninata.users_app.manager


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
    ]
