# Generated by Django 4.2 on 2023-05-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilebaseinformation',
            options={'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelOptions(
            name='userapp',
            options={'verbose_name_plural': 'Потребители'},
        ),
        migrations.AddField(
            model_name='userapp',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Моля използвайте по-сложна парола.'}, max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
