# Generated by Django 4.2 on 2023-05-09 05:32

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_alter_profilebaseinformation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProfile',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=25, verbose_name='Име')),
                ('last_name', models.CharField(max_length=25, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='GuideProfile',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', cloudinary.models.CloudinaryField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('description', models.TextField()),
                ('certificate', cloudinary.models.CloudinaryField(max_length=255)),
                ('profile_id', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='users_app.baseprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='ProfileBaseInformation',
        ),
    ]
