# Generated by Django 4.2 on 2023-06-07 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_create_anonymous_app_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guideprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='guideprofile',
            name='last_name',
        ),
    ]
