# Generated by Django 4.2 on 2023-05-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_alter_baseprofile_options_alter_guideprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousAppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
    ]
