version: '3.4'

services:
  web:
    build: ./
    command: gunicorn lekipohodivplaninata.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./staticfiles:/tmp/lekipohodivplaninata/staticfiles
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgres
      - cache
      - celery

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1123QwER
      POSTGRES_USER: postgres
      POSTGRES_DB: lekipohodi
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  cache:
    image: redis
    restart: always
    ports:
      - '6379:6379'

  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./staticfiles:/tmp/lekipohodivplaninata/staticfiles/
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - web

  celery:
    build: ./
    command: celery -A lekipohodivplaninata worker -l info
    volumes:
      - ./staticfiles:/tmp/lekipohodivplaninata/staticfiles
    env_file:
      - .env
    depends_on:
      - postgres
      - cache
`