# Generated by Django 4.2 on 2023-05-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
    ]
