# Generated by Django 4.2 on 2023-05-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hike', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HikeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title',
                 models.CharField(help_text='Моля попълнете типа на похода', max_length=30, verbose_name='Заглавие')),
            ],
            options={
                'verbose_name': 'Тип поход',
                'verbose_name_plural': 'Типове походи',
            },
        ),
    ]
