# Generated by Django 4.2 on 2023-06-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0002_create_hike_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HikeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Моля попълнете вида трудност', max_length=30, verbose_name='Заглавие')),
            ],
            options={
                'verbose_name': 'Ниво на поход',
                'verbose_name_plural': 'Нива на походи',
            },
        ),
    ]
