# Generated by Django 4.2 on 2023-06-01 13:15

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0003_create_hike_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='HikeMorePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Снимка')),
            ],
            options={
                'verbose_name': 'снимка',
                'verbose_name_plural': 'Допълнителни снимки към походи',
            },
        ),
    ]
