# Generated by Django 4.2 on 2023-05-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0005_hike'),
    ]

    operations = [
        migrations.AddField(
            model_name='hike',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
