# Generated by Django 4.2 on 2023-06-06 19:082/ot-tuk-do-tam-10yu-07-08-2023/

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0006_add_and_remove_slug_field_for_hike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
