# Generated by Django 4.2 on 2023-06-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hike', '0006_auto_generate_slug_field_in_hike_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
            preserve_default=False,
        ),
    ]
