# Generated by Django 4.2 on 2023-05-14 20:10

from django.db import migrations
from django.utils.text import slugify

from lekipohodivplaninata.core.utils import from_cyrillic_to_latin


def add_slugs(apps, schema_editor):
    Hike = apps.get_model('hike', 'Hike')

    treks = Hike.objects.all()

    for hike in treks:
        hike.slug = slugify(from_cyrillic_to_latin(hike.title))

    Hike.objects.bulk_update(treks, fields=['slug'])


def delete_slugs(apps, schema_editor):
    Hike = apps.get_model('hike', 'Hike')

    treks = Hike.objects.all()

    for hike in treks:
        hike.slug = None

    Hike.objects.bulk_update(treks, fields=['slug'])


class Migration(migrations.Migration):
    dependencies = [
        ('hike', '0006_hike_slug'),
    ]

    operations = [
        migrations.RunPython(add_slugs, delete_slugs)
    ]
