# Generated by Django 4.2 on 2023-05-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0007_auto_fill_slug_field_of_every_hike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='slug',
            field=models.SlugField(blank=True, default=None, unique=True),
            preserve_default=False,
        ),
    ]
