# Generated by Django 4.2 on 2023-06-12 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0008_create_hike_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='type',
            field=models.ForeignKey(help_text='Моля изберете тип за похода', on_delete=django.db.models.deletion.RESTRICT, to='hike.hiketype', verbose_name='Тип на похода'),
        ),
    ]
