# Generated by Django 4.2 on 2023-05-21 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0008_alter_hike_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hikemorepicture',
            old_name='title',
            new_name='image',
        ),
    ]
