# Generated by Django 4.2 on 2023-06-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0009_alter_hike_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='more_pictures',
            field=models.ManyToManyField(help_text='Тук можете да добавите допълнителни снимки за похода', to='hike.hikemorepicture', verbose_name='Допълнителни снимки'),
        ),
    ]
