# Generated by Django 4.2 on 2023-05-24 18:28

from django.db import migrations, models
import lekipohodivplaninata.hike.validators


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0009_rename_title_hikemorepicture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='event_date',
            field=models.DateField(help_text='Моля изберете дата за похода', validators=[lekipohodivplaninata.hike.validators.validate_before_today], verbose_name='Дата на похода'),
        ),
    ]
