# Generated by Django 4.2 on 2023-05-24 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hike', '0010_alter_hike_event_date'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelWith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SignUpForHike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('participants_number', models.PositiveIntegerField()),
                ('signed_on', models.DateTimeField(auto_now_add=True)),
                ('hike_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hike.hike')),
                ('travel_with', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.travelwith')),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='contenttypes.contenttype')),
            ],
        ),
    ]
