# Generated by Django 4.2 on 2023-06-03 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('hike', '0008_create_hike_additional_info'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpForHike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('travel_with',
                 models.PositiveSmallIntegerField(choices=[(0, 'Организиран Транспорт'), (1, 'Собствен Транспорт')])),
                ('adults_numbers', models.PositiveIntegerField()),
                ('children_numbers', models.PositiveIntegerField()),
                ('signed_on', models.DateTimeField(auto_now_add=True)),
                ('hike_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hike.hike')),
                ('user_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='contenttypes.contenttype')),
            ],
        ),
    ]
