# Generated by Django 4.2 on 2023-06-01 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0007_alter_hike_slug'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('base', '0002_create_travel_with'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpForHike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('participants_number', models.PositiveIntegerField()),
                ('signed_on', models.DateTimeField(auto_now_add=True)),
                ('hike_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hike.hike')),
                ('travel_with', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.travelwith')),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='contenttypes.contenttype')),
            ],
        ),
    ]
