# Generated by Django 4.2 on 2023-06-13 11:33

from django.db import migrations, models
import lekipohodivplaninata.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_signupforhike_is_confirmed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HikeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.PositiveSmallIntegerField(validators=[lekipohodivplaninata.core.validators.ValueInRangeValidator(1, 10)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('more_info', models.ManyToManyField(to='base.hikeevaluationmoreinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
