# Generated by Django 4.2 on 2023-06-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_create_hike_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupforhike',
            name='is_confirmed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signupforhike',
            name='is_recommend',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
