# Generated by Django 4.2 on 2023-06-13 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0010_alter_hike_more_pictures'),
        ('users_app', '0005_remove_guideprofile_first_name_and_more'),
        ('base', '0008_alter_hikeevaluation_assessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='HikeEvaluationUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users_app.baseprofile')),
            ],
        ),
        migrations.RemoveField(
            model_name='hikeevaluation',
            name='more_info',
        ),
        migrations.AddField(
            model_name='hikeevaluation',
            name='hike_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hike.hike'),
        ),
        migrations.DeleteModel(
            name='HikeEvaluationMoreInfo',
        ),
        migrations.AddField(
            model_name='hikeevaluation',
            name='users',
            field=models.ManyToManyField(to='base.hikeevaluationusers'),
        ),
    ]
