# Generated by Django 4.2 on 2023-07-16 16:38

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0010_alter_hike_more_pictures'),
        ('base', '0010_slider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupforhike',
            old_name='is_recommend',
            new_name='is_presence',
        ),
        migrations.AlterField(
            model_name='slider',
            name='hike_id',
            field=models.OneToOneField(help_text='Моля изберете един от посочениет походи', on_delete=django.db.models.deletion.RESTRICT, to='hike.hike', verbose_name='Изберете поход'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=cloudinary.models.CloudinaryField(help_text='Тук трябва добавите основна снимка за похода', max_length=255, verbose_name='Снимка'),
        ),
    ]
