# Generated by Django 4.2 on 2023-07-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_socialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Моля въведете телефон за контакт с вас', max_length=13, verbose_name='Телефон за контакт')),
                ('email_for_contact', models.EmailField(help_text='Моля въведете емайла с когото ще могат да се свързват с вас', max_length=254, verbose_name='Емейл за контакт')),
            ],
        ),
    ]
