# Generated by Django 4.2.3 on 2023-07-29 21:42

from django.db import migrations, models
import lekipohodivplaninata.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_settings_social_media_socialmedia_icon_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Настройка', 'verbose_name_plural': 'Настройки'},
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name': 'Социална медия', 'verbose_name_plural': 'Социални медии'},
        ),
        migrations.RemoveField(
            model_name='hikeevaluation',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='hikeevaluation',
            name='comment',
        ),
        migrations.AddField(
            model_name='hikeevaluationusers',
            name='assessment',
            field=models.PositiveSmallIntegerField(null=True, validators=[lekipohodivplaninata.core.validators.ValueInRangeValidator(1, 10)]),
        ),
        migrations.AddField(
            model_name='hikeevaluationusers',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='social_media',
            field=models.ManyToManyField(blank=True, to='base.socialmedia'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='fontawesome_icon',
            field=models.CharField(blank=True, help_text='Влизате в https://fontawesome.com/search и избирате иконата която желате, след което селектирате името на класа и го поставяте тук. Например: ＜i class="fa-brands fa-facebook"＞ се поставя само fa-brands fa-facebook', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='icon_color',
            field=models.CharField(blank=True, help_text='Поставяте само 6 цифрения код. Например HEX кода е #3b5998, вие поставяте само 3b5998', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='name',
            field=models.CharField(help_text='Това е името което ще се показва в долната част на сайта.', max_length=20),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='url',
            field=models.URLField(help_text='Поставяте линка на социалната медия'),
        ),
    ]
