# Generated by Django 4.2.3 on 2023-07-29 21:45

from django.db import migrations, models
import lekipohodivplaninata.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0016_alter_settings_options_alter_socialmedia_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hikeevaluationusers',
            name='assessment',
            field=models.PositiveSmallIntegerField(
                validators=[lekipohodivplaninata.core.validators.ValueInRangeValidator(1, 10)]),
            preserve_default=False,
        ),
    ]
