# Generated by Django 4.2.3 on 2023-07-30 08:37

from django.db import migrations, models
import lekipohodivplaninata.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_hikeevaluationusers_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hikeevaluationusers',
            name='assessment',
            field=models.PositiveSmallIntegerField(null=True, validators=[lekipohodivplaninata.core.validators.ValueInRangeValidator(1, 10)]),
        ),
        migrations.AlterField(
            model_name='siteevaluation',
            name='assessment',
            field=models.PositiveSmallIntegerField(null=True, validators=[lekipohodivplaninata.core.validators.ValueInRangeValidator(1, 10)]),
        ),
    ]
