# Generated by Django 4.2.3 on 2023-08-11 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_subscribe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
