# Generated by Django 4.2.3 on 2023-08-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMAPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('imap_server', models.CharField(max_length=100)),
                ('imap_port', models.PositiveSmallIntegerField()),
                ('imap_username', models.CharField(max_length=100)),
                ('imap_password', models.CharField(max_length=100)),
            ],
        ),
    ]
