# Generated by Django 4.2.3 on 2023-08-12 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_imapsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imapsettings',
            name='email_address',
        ),
    ]
